apiVersion: v1
kind: Service
metadata:
  name: docx-to-pdf-app-service
spec:
  type: LoadBalancer  
  selector:
    app: docx-to-pdf-app
  ports:
  - protocol: TCP
    port: 80         
    targetPort: 5000 
