apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app  # This should match the label used in the Deployment
  ports:
    - protocol: TCP
      port: 80             # The port on which the service will be exposed
      targetPort: 5000     # The port your Flask app listens on inside the container
  type: LoadBalancer       # This will expose the service to the external world
